[WIP]Improve error handling
ca-risken/gateway pull request #126
Opened 2022-09-01 04:29 UTC by mmmknt

2022-09-02 08:48 UTC, hnts requested changes

2022-09-02 08:48 UTC, hnts commented on authorizer.go
> +			appLogger.Errorf(ctx, "failed to read body, err=%+v", err)
細かいですが、loggerの場合は最初大文字ですかね？

2022-09-02 09:22 UTC, mmmknt commented on authorizer.go
> +			appLogger.Errorf(ctx, "failed to read body, err=%+v", err)
他のログ出力と合わせて先頭を大文字に変更しました。（他の変更箇所も対応済み）

2022-09-02 09:24 UTC, mmmknt commented on authorizer.go
> +			appLogger.Errorf(ctx, "failed to read body, err=%+v", err)
また、grpc connectionの生成でエラーになった際にFatalログ出力する階層を間違えていたので、mainでFatalLogを出力するよう対応しています。

2022-09-02 11:21 UTC, gassara-kys approved these changes
LGTM

2022-09-05 01:24 UTC, hnts approved these changes

2022-09-05 01:33 UTC, hnts commented
LGTM

2022-09-05 02:08 UTC, merged